version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file sample.json --s3-bucket saiaungpyae --output-template-file output.json
artifacts:
  type: zip
  files:
    - sample.json
    - output.json