version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file sample.yaml --s3-bucket saiaungpyae --output-template-file output.yaml
artifacts:
  type: zip
  files:
    - sample.yaml
    - output.yaml