version: 0.1
phases:
  install:
    commands:
      - npm install
      - pip install --upgrade awscli
      
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      # - aws s3 cp --recursive public/ s3://saiaungpyae/public/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - aws lambda list-functions
      - zip -r ggwp.zip .
      - aws lambda update-function-code --function-name HelloWorld --zip-file fileb://./ggwp.zip
      - aws configure set default.region ap-southeast-1
      - aws lambda list-functions
      - aws lambda update-function-code --function-name ggwp --zip-file fileb://./ggwp.zip
artifacts:
  type: zip