version: 0.1
phases:
  install:
    commands:
      - npm install
      
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      # - aws s3 cp --recursive public/ s3://saiaungpyae/public/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - zip -r ggwp.zip .
      - aws lambda update-function-code --function-name HelloWorld --zip-file fileb://./ggwp.zip
      - aws s3 cp ggwp.zip s3://cynthiasoe/ggwp.zip
artifacts:
  type: zip