version: 0.1
phases:
  install:
    commands:
      - npm install
      - pip install --upgrade awscli
      
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template input.yml --s3-bucket saiaungpyae --output-template output.yml
artifacts:
  type: zip
  files:
    - output.yml