version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file samTemplate.json --s3-bucket saiaungpyae --output-template-file outputSamTemplate.json
artifacts:
  type: zip